### PR TITLE
Code reorganization + CMake

### PR DESCRIPTION
**Pull request by hadim**
Here is a complete reorganization of the repository. I merged the `master`, `qvina-w` and `qvina2_1buffer` in one single branch. Source code is split in `src` in `src/vina`, `src/qvina2` and `src/qvinaw`.

I also switched the build system to CMake and added test data in `data/` so it's easy to quickly test if the program is working or not.

My intention is to submit this program to [conda-forge](https://conda-forge.org/) for inclusion. That way binaries will be automatically built for Linux, OSX, and Windows.

It would be nice also for you to add a release tag ass suggested in #3 so it's easier for people to relate a binary to a specific revision of the source code.

### CODE REVIEW

**Comment by aalhossary** [comment]
Sounds good.
Let me review it over the weekend.

**Comment by hadim** [comment]
Here is the submission for conda-forge inclusion: https://github.com/conda-forge/staged-recipes/pull/11050

This PR will need to be merged and a release tagged before the conda recipe gets merged.

**Comment by hadim** [comment]
The package has been integrated so you can now install qvina on Linux with:

```bash
conda config --add channels conda-forge
conda install qvina
```

At the moment the package is only available for Linux but we should build it for OSX and Windows.

The package is based on my fork but I will update it once this PR has been reviewed, merged and a tag released.

**Comment by hadim** [comment]
Packages are now available for Windows and OSX: https://anaconda.org/conda-forge/qvina

I only tested on Windows on my personal computer and it works well (including multithreading).

**Comment by aalhossary** [comment]
Dear Hadrien Mary @hadim ,
I am sorry I couldn't review your PR yet. I appreciate your patience (most probably I won't have time before end of March).
Meanwhile, may I ask you for a few changes, please?

1. May you please keep the common files among Vina, Qvina2, and qvina-w in a unique folder, and only changed files (and build scripts of course) to be in a separate folder? That should minimize any future effort of update. instead of updating three almost identical files, the update can be done only once. This is an **important** request, and it is actually the reason why I was reluctant to separate them into three separate repositories till now.

1. Thank you for reformatting the files. May you please adjust the format to have the opening brackets "{" on the same line with the if or for statement. That should enhance readability of the code.

Thank you in advance

Sincerly
Amr

**Comment by hadim** [comment]
I made this PR to be able to package Vina in order to ensure better reproducibility of workflows using Vina and also when possible to allow running it on OSX and Windows. 

I agree common files should have been kept common but this issue was here before this PR. I don't think I will fix it myself (mainly because I am lacking time). I would prefer someone else to do it in another PR.

**Comment by hadim** [comment]
(By the way the package is also available on Windows and OSX. I only tested Windows at the moment: https://anaconda.org/conda-forge/qvina)

**Comment by aalhossary** [comment]
Dear Hadrien Mary @hadim  ,
Do you have time now?

By the way,  you say
>I agree common files should have been kept common but this issue was here before this PR

Either we are talking about different things, or you didn't get my point.
Actually no. You created three folders (one for Vina, QVina2, and QVina-W each), and copied (duplicated) all the files, instead of keeping common files in one folder and making three different folders for new or modified files only.

**Comment by hadim** [comment]
Before this PR, the issue was here since everything was separated in different git branches. Now there are just separated in the same git branch but in different folders.

I am sorry but I don't have any more time to dedicate to this PR.

Merging everything together should be straightforward. Feel free to do it!

**Pull request closed without merging**
